# Только смена пола вокала (было: female)
captions: "jazz pop, soft jazz, woman voice, calm, melancholic, piano, guitar, drums, intimate"
lyrics: |
  I waited 'til I saw the sun
  I don't know why I didn't come
  I left you by the house of fun
  Don't know why I didn't come
  Don't know why I didn't come
